### ISSUE TITLE
Image upload on your demo page is not secure and private!

### ISSUE THREAD

**Issue by l0k9j** [stanfordmlgroup/blm#1]
If you genuinely care about privacy please serve your upload web page over HTTPS! Set up is [easy, quick, free and important](https://www.eff.org/encrypt-the-web). Solution to privacy is not _just_ more AI.

![image](https://user-images.githubusercontent.com/64646074/88390386-c4033b00-cda7-11ea-9d9e-3a5333cf0276.png)

Cool tool by the way!

**Comment by sharonzhou** [comment]
Thanks so much for reaching out! The original site is indeed on https: https://gcp-sharon-research.appspot.com/. The url we're using is a proxy url that just redirects there, but Stanford subdomains sadly creates an alias that is in http. We are working to help alleviate that since I definitely agree, this is not optimal! If you have any ideas, please let me know. Some other cool folks have proposed some solutions so we’re going to try them out. Thanks so much :)

**Comment by sharonzhou** [comment]
Alas, the proxy doesn't let us. We're going to create a separate branch for an `offline` version that a gracious community member has contributed!

**Comment by sharonzhou** [comment]
Woo it's officially https!!

**Comment by l0k9j** [comment]
Brilliant, thanks for making that change!
